default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development: &development
  <<: *default
  database: turntable_development
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
